# Generated by Django 4.2.1 on 2023-06-01 21:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_user_city_user_dateofbirth_user_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOCKVouchers',
            fields=[
                ('voucherID', models.IntegerField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(default=None, max_length=30)),
                ('voucherCategory', models.CharField(default=None, max_length=30)),
                ('storeType', models.CharField(default=None, max_length=30)),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateOfAcquire', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateOfExpiry', models.DateTimeField(default=django.utils.timezone.now)),
                ('redeemed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('typeID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherCategory',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('voucherID', models.IntegerField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(default=None, max_length=30)),
                ('voucherCategory', models.CharField(default=None, max_length=30)),
                ('storeType', models.CharField(default=None, max_length=30)),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateOfAcquire', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateOfExpiry', models.DateTimeField(default=django.utils.timezone.now)),
                ('redeemed', models.BooleanField(default=False)),
                ('daysBeforeAlert', models.IntegerField(default=7)),
                ('walletID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(blank=True, max_length=30, null=True)),
                ('houseNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.ForeignKey(default=None, max_length=30, on_delete=django.db.models.deletion.SET_DEFAULT, to='mysite.storetype')),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('alertID', models.IntegerField(primary_key=True, serialize=False)),
                ('alertDate', models.DateField()),
                ('aletHour', models.TimeField()),
                ('voucherID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mysite.vouchers')),
            ],
        ),
    ]
