# Generated by Django 4.1.7 on 2023-04-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_vouchers_ammount_alter_vouchers_redeemed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(max_length=50, unique=True)),
                ('expiration_date', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField()),
            ],
        ),
    ]
