# Generated by Django 4.1.7 on 2023-04-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_rename_usage_limit_temporaryvoucher_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='walletID',
        ),
        migrations.RemoveField(
            model_name='vouchers',
            name='walletID',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
