# Generated by Django 4.1.7 on 2023-04-13 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_wallet'),
        ('mysite', '0006_remove_alerts_walletid_remove_vouchers_walletid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='walletID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.wallet'),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='ammount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
