# Generated by Django 4.1.7 on 2023-04-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_delete_temporaryvoucher_alter_vouchers_voucherid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=50, unique=True)),
                ('expiration_date', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='voucherID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
