# Generated by Django 4.1.7 on 2023-04-14 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_vouchers_dateofacquire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='dateOfAcquire',
            field=models.DateField(default=datetime.datetime(2023, 4, 14, 15, 2, 58, 84675)),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='dateOfExpiry',
            field=models.DateField(default=datetime.datetime(2023, 4, 14, 15, 2, 58, 84675)),
        ),
    ]
