# Generated by Django 4.1.7 on 2023-04-14 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_vouchers_dateofacquire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='dateOfAcquire',
            field=models.DateField(default=datetime.datetime(2023, 4, 14, 15, 31, 34, 658125)),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='dateOfExpiry',
            field=models.DateField(default=datetime.datetime(2023, 4, 14, 15, 31, 34, 658125)),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='storeType',
            field=models.CharField(default='undefined', max_length=30),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='voucherCategory',
            field=models.CharField(default='undefined', max_length=30),
        ),
    ]
