# Generated by Django 4.1.7 on 2023-05-06 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_alter_vouchers_dateofacquire_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayWiseUser',
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='dateOfAcquire',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 15, 38, 59, 841521)),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='dateOfExpiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 15, 38, 59, 841521)),
        ),
    ]
