# Generated by Django 4.1.7 on 2023-05-06 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_alter_vouchers_dateofacquire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='dateOfAcquire',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 15, 40, 26, 3383)),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='dateOfExpiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 15, 40, 26, 3383)),
        ),
    ]
