# Generated by Django 4.1.7 on 2023-05-08 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0029_alter_vouchers_dateofacquire_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryVoucher',
        ),
        migrations.AddField(
            model_name='vouchers',
            name='storeName',
            field=models.CharField(default='undefined', max_length=30),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='dateOfAcquire',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 18, 4, 7, 289666)),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='dateOfExpiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 18, 4, 7, 289666)),
        ),
    ]
