# Generated by Django 4.1.7 on 2023-05-08 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0030_delete_temporaryvoucher_vouchers_storename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOCKVouchers',
            fields=[
                ('voucherID', models.IntegerField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(default='undefined', max_length=30)),
                ('voucherCategory', models.CharField(default='undefined', max_length=30)),
                ('storeType', models.CharField(default='undefined', max_length=30)),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateOfAcquire', models.DateTimeField(default=datetime.datetime(2023, 5, 8, 18, 14, 29, 791204))),
                ('dateOfExpiry', models.DateTimeField(default=datetime.datetime(2023, 5, 8, 18, 14, 29, 791204))),
                ('redeemed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='dateOfAcquire',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 18, 14, 29, 791204)),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='dateOfExpiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 18, 14, 29, 791204)),
        ),
    ]
