# Generated by Django 4.1.7 on 2023-05-12 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0034_alter_mockvouchers_dateofacquire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockvouchers',
            name='dateOfAcquire',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mockvouchers',
            name='dateOfExpiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='dateOfAcquire',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
