# Generated by Django 4.1.7 on 2023-05-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0035_alter_mockvouchers_dateofacquire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='daysBefoAlert',
            field=models.IntegerField(default=7, max_length=3),
        ),
    ]
