# Generated by Django 4.1.7 on 2023-05-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0036_vouchers_daysbefoalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='daysBefoAlert',
            field=models.IntegerField(default=7),
        ),
    ]
