# Generated by Django 4.1.7 on 2023-05-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0037_alter_vouchers_daysbefoalert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vouchers',
            old_name='daysBefoAlert',
            new_name='daysBeforeAlert',
        ),
    ]
