# Generated by Django 4.1.7 on 2023-05-06 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayWiseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(blank=True, max_length=30, null=True)),
                ('houseNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('dateOfBirth', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
