# Generated by Django 4.1.7 on 2023-05-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_paywiseuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayWiseUser',
        ),
    ]
