# Generated by Django 4.1.7 on 2023-05-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_paywiseuser_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paywiseuser',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paywiseuser',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
